language: android

install: true

sudo: true

notifications:
  email: false
  
addons:
  sonarcloud:
    branches:
    - develop
    - master
    token:
      secure: "Ar9iTRwV3kfKL2edaezUS0CSZ1ry6dDZekz6aiGe4QlsvbBrQ8WOwsIat878Kemxa+3JCNnZhFAlhFwF/I9/zrdp1z3XEvZi8LM3pFVnQGVrMErUHjEtcnlZpMSdDN6gcIrZ8jnLhTXOigHTLgV4MISWGia+6bLGh63MTCNl0GArw8O3uPVBgJicwIIRfTJ4/dGmDmAmU0zSrptx4X15SFKF34Rwbz6+jh1Z/qCE3x/ZxZ57ZCbrv4rv9snY9pfljrBAzwq5OF1wpTdgVRwA/lPd7PHGDbZ6wt+u9XCC1NRjW5slCOnkTYtPh+Zao/ZyYWCk5yAZ5MbzVSYw8Kb6yy6xtnIA8J4VuYQoSnJZJ+qpWmn6AdY+TKIMD0gSBfp1THARGgB/8/2aPYGBLvtzycU1601ZBy+RjO/tR86j3QUS6hFY1cBFc3Tg66MaxkkSDBE0qx46dw6/OE9nP5LUKGGBwnBpjTZcdE/1E1WCjXHP4U4mVvq+XKnqCgjkadGJk/aY6FOgv6+NBL8KfouK+6IH3VdV/gIoTzJbd4OKHW1EHfVfxVCL6w/M84wdPvJeEpzXhx8AeVCBt7/7LM4F+FIocCwEjiq+5BA7yVqG8uTqefaRI/b7OdihgTjFKmwDS2VZsaiQBx4ALwveEnPk0Ro8PQRCXT5+WIJ5Jj8VAt8="

jdk: oraclejdk8

android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # BuildTools version used by project
    - build-tools-26.0.2

    # SDK version to compile project
    - android-26

    # Additional components
    # - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22

script: ./deploy.sh

before_install:
  - openssl aes-256-cbc -K $encrypted_6a3a5fc3045a_key -iv $encrypted_6a3a5fc3045a_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - gem install supply

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '$HOME/.sonar/cache'
    - '.gradle'

env:
  global:
    - secure: "IlOrlw4ot42cycrS8DzYhsT+prZH8Md9HqExABKPuU1YiIn16MzrTMY8BwbGUYlv6Whe1eLZIdGy0xbAsMoNEVuotoTWd4pudwcYsdKbQsk2DECCQvm0887SvvlsGR1uN9M6LlJBBhRjhqTDbA/BlXiQZqu5O7qmOf/ZUN3MG+KZnoqXOk+jyxHqzbZrk6VdVWp85i7UqURkmFcI4mxYXV5SxKjxk3lZFIHpIY6fTln4WTBkuNKr6TgjuBEWDDFUoeloTdYEVi8NLPDdwGYXeILjv6ZGJJaxySpl+m80uSvsA+E6y8T0XJnnYEd/h+aVlndhilkuOAfIhYLql2bew8vRoc92mIgqw6tKbsZQNWsE9l2eSnBWs2rY9e1ctF3ubDfdaq8FDjrY0P/g3wQqrszyI85me/vPgBMi3kuja+sIKaKs05WA/x7oEqYz0MmX0PP4TYXi/Bp6fdU907bTyPSslYuAienmsdO4h0aWLxto8qc0fcjfBLsc82oNiq4Dc/riAvktwUms+G2BRp1F4ns2mWMz2GwsXhAN7CtBTNVj4BEI0aSE6Ar8CGBbJVT+Jh/oNXRU17LPN9YPdWQB88YB8wLOl/FMXE3fAJSbKZmhxUIbw52PPP7vvyXCLL8iSyH0WB/GZhafp/MNaowmLKFhIgGZTRJxHGKvY7JrBxE="
    - secure: "zvBLAjpzM60JYcwRnnx9uAoVhu0EbOzE3ALVf+zwwUa5BYgaKqowgu1MEo+/6W9EaKZirKmfMQt3os7GcV18uEjfXkP781miFtqBP7X15Q+ebFz9BYGiTp7pt+xEOTfa9m3MElwTh1c2HfgcCamk7Y9LjAKklhuC7ebRFMMMmvG+grr/s7PIzXrwEq3/KW8SjERCeiBVUs3EouFDdM9wIjI2YvtHNf56Om7/TLRc8M2lQOSxvcYGelqabn/5B/xYDWyfmk8wONuMsQZXr2bE3GPEj5uJkihsOvqhfDicP/PEVRKuteMgn4Uu31e9jm0zqvbiHuZARpFDYpY2JC90/ZN/wBBKIv8ddnOPWMaeZ+g7xJQp5o4KkBhIwci/hPa94510EyJ3T76EdHfjdF7EfjR2Lul1OhhN5C9Hx89znUFmWKNe25ma6SCm/UncR58kSDox6pt4JSNef7/kcmakMIV4PZFmcAwm+DQtcmAOw/QW9k07D28ARSI26BUAG8Pe5m9DTfKpZiVLuLZ1m8AvOk6sX4UhZAcu12qbVtUmqpFze7P5uLXhu+0fT2Nv77dSOLPUr51q6sAcgbsXY4MDRT157t9HfVfgMsQ0u5ts45mfcPmHCU5/Ip1CSEaIS+CT8cU//p2enZ59ONhGPIK6BaOiZkPe1BmqyUjI0oyOFno="
    - secure: "LaIzZNO+tPAP5yErwnfurXVcZcmLgcYjqHZ/FdtIerwxqQd3iio5v+19U4NIapr8bs4goPrmm5OpjsDGikSXgcxKBskuAaa40mT7IoVs53atWVYX5PCPEw9IcjA9JfAB3GtCbv4QFmHXWamY03GUE5zPfG1yzzCsBXIaXj0iP2zR4qZQSBI8kO1HUUxiRIRR191j2roCPsAXNoQqxpxEmKoVJnVYoJJj2kBIQGfxZfhlWP7ghne/dMOIyBy3Z8Rmrj04GgPudFVS5GmTV2zNZ6vj/SrTyKTaGLrKDjHqV7pd/N4AXCXiwPNlJekThQ2HcRTf7XZGbsXHgQsmtdjy+mKISD4DVkOc0qWnZR03weMlkWp3pMO6J0mNtdusCzSIa/7XDzjsAFnK2NcMhQih+PxzLrv/8beyk3FAlfJ+hAjcY1pokVXYFHgZno1W1N8zTcqw6VNpssmiQKKtMqQi1j5cKRDReTzvB3AYvxjk6EwWmjJrljEvfZuZuEkVsv6E5Ow3O7+TK+XiY0ojmskUl8Wj21gChB6oqEoormwBWcYyCRbjkSugOsh+raTpm0z7vujL1/LKHDYozP2FMD8Ky63hPXHyjviVDD63EOfT3N4uBMD1Udw/IWme65DDjvGl5x+Yp2vSeb5Wr9FlwHqaDlnIfYbHYsdA1QvFDMOyCbo="

